obj-$(CONFIG_AW_AXP_NEW) += axp-core.o
obj-$(CONFIG_AW_AXP_NEW) += axp-powerkey.o
obj-$(CONFIG_AW_AXP_NEW) += axp-depend-init.o
obj-$(CONFIG_AW_AXP_NEW) += axp-depend-set.o
obj-$(CONFIG_AW_AXP_NEW) += axp-charger.o
obj-$(CONFIG_AW_AXP_NEW) += axp-charger-dt.o
obj-$(CONFIG_AW_AXP_NEW) += axp-gpio.o
obj-$(CONFIG_AW_AXP_NEW) += axp-regulator.o
obj-$(CONFIG_AXP_NMI_USED) += nmi/sunxi-nmi.o

#AXP152
obj-$(CONFIG_AW_AXP152) += axp152/axp152.o
obj-$(CONFIG_AW_AXP152) += axp152/axp152-regu.o
obj-$(CONFIG_AW_AXP152) += axp152/virtual152.o
obj-$(CONFIG_AW_AXP152) += axp152/virtual152_dev.o

#AXP22X
obj-$(CONFIG_AW_AXP22) += axp22/axp22.o
obj-$(CONFIG_AW_AXP22) += axp22/axp22-regu.o
obj-$(CONFIG_AW_AXP22) += axp22/axp22-charger.o
obj-$(CONFIG_AW_AXP22) += axp22/axp22-gpio.o
obj-$(CONFIG_AW_AXP22) += axp22/virtual22.o
obj-$(CONFIG_AW_AXP22) += axp22/virtual22_dev.o
